baseURL = "https://alex11br.github.io/"
languageCode = "en-us"
title = "Popa Ioan Alexandru"
theme = "PaperMod"
copyright = "Feel free to do whatever with my content, unless another stricter license is specified."

[markup.highlight]
style = "dracula"

[outputs]
home = ["HTML", "RSS"]

[[menu.main]]
name = "Posts"
url = "posts"
weight = 1

[[menu.main]]
name = "Projects"
url = "projects"
weight = 3

[[menu.main]]
name = "Contact"
url = "contact"
weight = 10

[params]
disableAnchoredHeadings = true
disableSpecial1stPost = true
defaultTheme = "dark"
disableThemeToggle = true
ShowCodeCopyButtons = false
ShowFullTextinRSS = true
showtoc = true

[params.label]
icon = "/logo.jpg"
iconHeight = 32

[params.assets]
disableHLJS = true
